
print()
print('##########################################################')
print()

print()
print("=" * 60)
print("Inductor L2")
print("=" * 60)

print()
print("=" * 60)
print("CORE GEOMETRY")
print("=" * 60)
print(f"A_surface_L2 : {A_surface_L2*1e4:.4f} cm²    = {A_surface_L2:.6e} m²")
print(f"Ae_L2        : {Ae_L2*1e6:.4f} mm²    = {Ae_L2:.6e} m²")
print(f"le_L2        : {le_L2*1e3:.4f} mm     = {le_L2:.6e} m")
print(f"Ve_L2        : {Ve_L2*1e6:.4f} cm³    = {Ve_L2:.6e} m³")
print(f"N_L2         : {N_L2} turns")
print(f"lg_L2        : {lg_L2*1e3:.4f} mm     = {lg_L2:.6e} m")
print(f"B_peak_L2    : {B_peak_L2:.4f} T")
print(f"B_max        : {L2_specs['B_max']:.4f} T")
print(f"Bsat         : {L2_specs['Bsat']:.4f} T")
print(f"B_peak / Bsat: {B_peak_L2/L2_specs['Bsat']*100:.2f} %  (should be < 70%)")

print()
print("=" * 60)
print("WINDING")
print("=" * 60)
print(f"I_rated_RMS        : {I_rated_RMS:.4f} A")
print(f"I_rated_peak       : {I_rated_peak:.4f} A")
V_L2_RMS = Calculation_functions.Capacitor_voltage_RMS(V_C=V_L2, resolution_per_cycle=resolution_per_cycle, f=f)
I_L2_RMS = Calculation_functions.Capacitor_voltage_RMS(V_C=I_L2, resolution_per_cycle=resolution_per_cycle, f=f)
print(f"V_L2_RMS           : {V_L2_RMS[-1]:.4f} V")
print(f"I_L2_RMS           : {I_L2_RMS[-1]:.4f} A")
print(f"A_wire_L2_minimum  : {A_wire_L2_minimum*1e6:.4f} mm²")
print(f"d_wire_L2_minimum  : {d_wire_L2_minimum*1e3:.4f} mm")
print(f"N_parallel_wire_L2 : {N_parallel_wire_L2} strands")
print(f"A_wire_actual_L2   : {A_wire_actual_L2*1e6:.4f} mm²")
print(f"l_turn_L2          : {l_turn_L2*1e3:.4f} mm")
print(f"Rdc_L2             : {Rdc_L2*1e3:.4f} mΩ")

print()
print("=" * 60)
print("POWER LOSSES")
print("=" * 60)
print(f"P_c_L2     : {P_c_L2} W   (core losses per second)")
print(f"P_w_L2     : {P_w_L2} W   (winding losses per second)")
print(f"P_total_L2 : {P_total_L2} W   (total losses per second)")

print()
print("=" * 60)
print("TEMPERATURE")
print("=" * 60)
print(f"T_inductor_L2 : {T_amb} K  =  {T_amb - 273} °C")
print(f"R_th_L2       : {R_th_L2:.4f} K/W")
print(f"T_inductor_L2 : {T_inductor_L2} K  =  {T_inductor_L2 - 273} °C")
print(f"T_rated       : {L2_specs['T_insulation_rated']} K  =  {L2_specs['T_insulation_rated'] - 273:.1f} °C")
print(f"Margin        : {L2_specs['T_insulation_rated'] - T_inductor_L2} K  below rated")

print()
print("=" * 60)
print("LIFETIME")
print("=" * 60)
print(f"Lifetime_L2_series : {Lifetime_L2_series} years  (per second)")
print(f"Lifetime_L2        : {Lifetime_L2:.4f} years")
print(f"Lifetime_consumed  : {Lifetime_consumed_L2:.6e} %")

print()
print('##########################################################')
print()